### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by liamxg** [milos-agathon/animated-fire-map#3]
<img width="797" alt="image" src="https://github.com/milos-agathon/animated-fire-map/assets/46078579/1fc74792-9682-44f9-a1a0-e17515a16b4e">

**Comment by liamxg** [comment]
<img width="661" alt="image" src="https://github.com/milos-agathon/animated-fire-map/assets/46078579/c758e102-6b54-452d-8454-e2d7d47eb8a3">

**Comment by liamxg** [comment]
@milos-agathon

**Comment by dipunew** [comment]
Facing similar issue

**Comment by milos-agathon** [comment]
ggmap has a completely new setup that requires registration to be able to access tiles API. I suggest using `maptiles` package instead.
